server:
  port: 7101

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:7100/eureka/

turbine:
  app-config: srvc-uams,customer-ribbon
  cluster-name-expression: new String("default")

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: /usr/local/logs/${spring.application.name}.log
  #file: E:\\workspace_idea\\iot-platform\\logs\\turbine.log

spring:
  application:
    name: turbine

endpoints:
  refresh:
    enabled: true
    sensitive: true
  restart:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
security:
  user:
    name: admin
    password: admin123
management:
  security:
    roles: SUPERUSER
