server:
  port: 7103

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///E:/workspace_idea/iot-platform
          search-paths: config-repo

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: E:\\workspace_idea\\iot-platform\\logs\\config.log

