server:
  port: 7103

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///E:/workspace_idea/iot-platform
          search-paths: config-repo

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: E:\\workspace_idea\\iot-platform\\logs\\config.log

