server:
  port: 7103

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:/usr/local/deployed/config-repo
          #file:E:\\workspace_idea\\iot-platform\\config-repo

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:7100/eureka/

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: /usr/local/logs/${spring.application.name}.log
  #E:\\workspace_idea\\iot-platform\\logs\\config.log

endpoints:
  refresh:
    enabled: true
    sensitive: false
  restart:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false

