server:
  port: 8083
  context-path: /

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 60
    #lease-expiration-duration-in-seconds: 180
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/

spring:
  application:
    name: srvc-uams
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/eacha_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root$1234
      type: com.alibaba.druid.pool.DruidDataSource
      max-active: 10
      max-idle: 10
      min-idle: 1
      initial-size: 1
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false

mybatis:
  aliase-package: com.stanley.uams.domain

logging:
  level:
    com.stanley: debug
    org.springframework.web: info
  file: E:\\workspace_idea\\iot-platform\\logs\\srvc-uams.log
