server:
  port: 7102

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:7100/eureka/

zuul:
  routes:
    uams:
      path: /uams/**
      serviceId: srvc-uams
    customer-ribbon:
      path: /customer-ribbon/**
      serviceId: customer-ribbon

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: /usr/local/logs/${spring.application.name}.log
  #file: E:\\workspace_idea\\iot-platform\\logs\\zuul.log

spring:
  application:
    name: zuul

endpoints:
  refresh:
    enabled: true
    sensitive: false
  restart:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false
