server:
  port: 7100

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org.springframework: info
    com.netflix: info
  file: /usr/local/logs/${spring.application.name}.log
  #file: E:\\workspace_idea\\iot-platform\\logs\\eureka-server.log

spring:
  application:
    name: eureka-server

endpoints:
  refresh:
    enabled: true
    sensitive: true
  restart:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
security:
  user:
    name: admin
    password: admin123
management:
  security:
    roles: SUPERUSER
